### PR TITLE
Dockerize the project for nicer demo experience

### PR DESCRIPTION
**Pull request by spagnoloG**
Maybe a cool addition to the project. If you have any suggestions to fix anything please do comment:)

### CODE REVIEW

**Comment by jonppe** [comment]
I think this would be good addition to the project. 

Before noticing this PR, I already started doing my own non-conda version (https://github.com/jonppe/dust3r/commit/5089d1dcb867efd8556d4285a5eacc3a82c4bf41) but this was still helpful to find all the necessary apt packages. 
In fact there seems to be also another PR to add Dockerfile: https://github.com/naver/dust3r/pull/5

The non-conda installation feels somehow slightly more clean but I guess there's not much difference.

**Comment by spagnoloG** [comment]
I can try and integrate the venv version no problemo:) it looks cleaner yeah:)

**Comment by spagnoloG** [comment]
The image downloaded in the Dockerfile mentioned in pr #5 is kinda large (10GB) [nvidia containers list](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch/tags). But lets use it as it has nvidia kernel options available (other image did not have them) and croco model can be successfully installed now.

**Comment by spagnoloG** [comment]
Now it is cleaned up thanks @jonppe <3 !

**Comment by yocabon** [comment]
Thanks a lot.

**Pull request merged**
